"""initial tables

Revision ID: 0001
Revises:
Create Date: 2026-10-05 03:04:41.233652
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dimensions",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("group_name", sa.String(length=50), nullable=False),
        sa.Column("lead_question", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("id BETWEEN 1 AND 8", name=op.f("ck_dimensions_id_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dimensions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'reviewer', 'approver', 'admin')", name=op.f("ck_users_role")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("business_unit", sa.String(length=200), nullable=False),
        sa.Column("sponsor", sa.String(length=200), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=True),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.CheckConstraint("mode IN ('plan', 'assess')", name=op.f("ck_projects_mode")),
        sa.CheckConstraint(
            "stage IN ('Idea', 'Feasibility', 'Build', 'Pilot / UAT', 'Production', 'On hold')",
            name=op.f("ck_projects_stage"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_projects_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_archived"), ["archived"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_projects_owner_user_id"), ["owner_user_id"], unique=False
        )

    op.create_table(
        "questions",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("number BETWEEN 1 AND 5", name=op.f("ck_questions_number_range")),
        sa.ForeignKeyConstraint(
            ["dimension_id"], ["dimensions.id"], name=op.f("fk_questions_dimension_id_dimensions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_questions_dimension_id"), ["dimension_id"], unique=False
        )

    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("feature", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "feature IN ('interview', 'evidence', 'brief', 'summary')",
            name=op.f("ck_ai_calls_feature"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_ai_calls_project_id_projects")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_ai_calls_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_calls")),
    )
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_calls_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_calls_user_id"), ["user_id"], unique=False)

    op.create_table(
        "ai_suggestions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=8), nullable=False),
        sa.Column("answer", sa.String(length=10), nullable=False),
        sa.Column("evidence", sa.String(length=600), nullable=False),
        sa.Column("source_excerpt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "answer IN ('Yes', 'Partly', 'No', 'Dont_know')", name=op.f("ck_ai_suggestions_answer")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'dismissed')", name=op.f("ck_ai_suggestions_status")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_ai_suggestions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_ai_suggestions_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_ai_suggestions_question_id_questions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_suggestions")),
    )
    with op.batch_alter_table("ai_suggestions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_suggestions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "answer_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=8), nullable=False),
        sa.Column("old_answer", sa.String(length=10), nullable=True),
        sa.Column("new_answer", sa.String(length=10), nullable=True),
        sa.Column("old_evidence", sa.Text(), nullable=False),
        sa.Column("new_evidence", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("changed_by", sa.String(length=36), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "new_answer IS NULL OR new_answer IN ('Yes', 'Partly', 'No', 'Dont_know')",
            name=op.f("ck_answer_history_new_answer"),
        ),
        sa.CheckConstraint(
            "old_answer IS NULL OR old_answer IN ('Yes', 'Partly', 'No', 'Dont_know')",
            name=op.f("ck_answer_history_old_answer"),
        ),
        sa.CheckConstraint(
            "source IN ('person', 'ai_interview', 'ai_evidence', 'confirm', 'undo')",
            name=op.f("ck_answer_history_source"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["users.id"], name=op.f("fk_answer_history_changed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_answer_history_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_answer_history_question_id_questions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_history")),
    )
    with op.batch_alter_table("answer_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_answer_history_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "answers",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=8), nullable=False),
        sa.Column("answer", sa.String(length=10), nullable=True),
        sa.Column("evidence", sa.String(length=600), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "answer IS NULL OR answer IN ('Yes', 'Partly', 'No', 'Dont_know')",
            name=op.f("ck_answers_answer"),
        ),
        sa.CheckConstraint(
            "source IN ('person', 'ai_interview', 'ai_evidence')", name=op.f("ck_answers_source")
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"], ["users.id"], name=op.f("fk_answers_confirmed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_answers_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("fk_answers_question_id_questions")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_answers_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("project_id", "question_id", name=op.f("pk_answers")),
    )
    op.create_table(
        "briefs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("lowest", sa.Float(), nullable=True),
        sa.Column("weakest", sa.JSON(), nullable=False),
        sa.Column("dimension_scores", sa.JSON(), nullable=False),
        sa.Column("answered", sa.Integer(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "verdict IN ('fix', 'go', 'ready', 'not_assessed')", name=op.f("ck_briefs_verdict")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_briefs_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_briefs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_briefs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_briefs")),
    )
    with op.batch_alter_table("briefs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_briefs_project_id"), ["project_id"], unique=False)

    op.create_table(
        "evidence_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("text_extract", sa.Text(), nullable=False),
        sa.Column("uploaded_by", sa.String(length=36), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_evidence_files_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_evidence_files_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_files")),
    )
    with op.batch_alter_table("evidence_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_files_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_files_project_id"))

    op.drop_table("evidence_files")
    with op.batch_alter_table("briefs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_briefs_project_id"))

    op.drop_table("briefs")
    op.drop_table("answers")
    with op.batch_alter_table("answer_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answer_history_project_id"))

    op.drop_table("answer_history")
    with op.batch_alter_table("ai_suggestions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_suggestions_project_id"))

    op.drop_table("ai_suggestions")
    with op.batch_alter_table("ai_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_calls_user_id"))
        batch_op.drop_index(batch_op.f("ix_ai_calls_project_id"))

    op.drop_table("ai_calls")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_dimension_id"))

    op.drop_table("questions")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_projects_archived"))

    op.drop_table("projects")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("dimensions")
    # ### end Alembic commands ###
